apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-credentials
  namespace: kafka
spec:
  encryptedData:
    aws-credentials.properties: AgAzbKUPa1E3QsAX0I+2X3/D2YCEvvaX1gFCrj70FuD4Dgc8fZo6O6JgwFY+NZxmTyeDVPBPntlUfyLXapS7kmFbjSiG8vsPM/4B9snakymIjMim+My7fdWJOOQ4dDK/UAvmluHuIIiDkJzHFpsfsh4Z8OlGunoAtma4GPTL315feTguauPfqSbWZKndT7pES4zxH9yptGvFLFiFxrBXzQDNM+QhIa50bMi29ouux32Cnc0JI7Q1TX19PcSNFV9e2bDJjuZ2ARLKRa1wTgUiWV8Ap4F6zFE8+u40r4mqz88qYoFY/vSiTAwTwJ72xYDCKSJqXoqHiA+5yuWjiLUau6lkUyt4yqTVu7S17xxxBqFOo8NPZpov6tQZL3c6ksBYSjg8/h6UDQzvwnvYsxL63L4BAM6U8AS/r4H2r4XTE0VpMkCZsfvuWwYhAtq0k9hjjJ773NESPrOk+ibQElznmuGQBib7pI3/HtyvWT8H4gaOZqDgl4GvO6eH64TPRpoHHygsUabl7BkRlVwyUylnDxsAUrPm7REsJrU/LCVyTuCzHYJrR7kglNNoLd8XucTtFfzV8lzuQXNZFORVR/NQPYvXC2gkZ8x8h5v215Pj+vmi48ZfuElSCseNrhjNXOOr/q3OhQYJBhKR3Msl/jzvH7nbb4Aummf6MIbWPQ3Y7rwdwpyRcfnf6cihoDmhbDE1+sxP4r+SQYXdMzH2FV//Jin5SJiaOC4Q+zwPeTSY/choP1fYOqqr2EFr7B1k7MiNXXut3ZBZi/qF/TqTiGPcSAtzRjjRx4FvSTnHFwMYtaw+S1G5HWJlymZMHB6g3h+K
  template:
    metadata:
      creationTimestamp: null
      name: aws-credentials
      namespace: kafka
    type: Opaque

