apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-credentials
  namespace: kafka
spec:
  encryptedData:
    aws-credentials.properties: AgB4LZIODoyFhOI2zPKRpkdyDL9I+OhCNQaOkJowTpHiINrD7TG73DUiPutYz9V8QEiOiMKQjBonwoLNqeIJegl9EGiLof2qkMymxIhalxYQQ4du0k0mWL2CI6ncarTDz5YnZm7WYRWR7G7YmEKPio/q4S6PYHsCJaaoHAHLUR/nn3zk4gOJ63APmg04TcN948e4nJG/LggpvbjwdxxInaUXzVQXdgJ38v+bgQynyPzX3/9SCbudgommgP8SPYaRmEE1Oo9BfAAngBSolf2c6RfzjdUYKKHZ0gT4GKoedwfp71fdE/GIt06YqWWKC7zoZBpeB0F0oFt5NrfN99Gunwr+PC43UHNHCoIG1QQtKboyilHbE2SIrnOp3NbgIIOK0rzSOJWP6BOmh7BnSJDbT+/6BmEbJqUD8RADfrX9zWGK1H5M49Fgn9230KgjdlfBG1qs+IZZMq6da6cBCEXUoA38bKDQuFhkkXn1aZtgLCQ9CXkOwzPmTDYlWk9Ilv6/tm1deOqjgtD6KZ2hv8xIKlnv9lpLfhQzgVPoDenjS/3u4dBUwYie9u98dMzB/QtDTddwfxtc2fG27/eh9zq009xUOXq5oGYlOGfiT1ytvUwSwfwYO0WTsLERpt8Y7ir4VTrKWxwHtXyAMFjB4YSCLUei3fkhhvPqpl9LO3/gKc5PNDHmKdHl7mpS8RXUXG+p3pOCc0W6bPU6H9/Q2zTVh+K0d60Uz8F04ZvK/nXkqUiQ5EqdgPD7t52zUpJueyRKO7yXV0+oO+GpbuRLlR7LjfBRgftF9cfGtHrepjQ7/JrddFATFyUsIM8mDBmGoU3N
  template:
    metadata:
      creationTimestamp: null
      name: aws-credentials
      namespace: kafka
    type: Opaque

