apiVersion: "kafka.strimzi.io/v1beta2"
kind: "KafkaConnector"
metadata:
  name: "sql-source-connector"
  labels:
    strimzi.io/cluster: kafka-connect-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  class: io.debezium.connector.sqlserver.SqlServerConnector
  tasksMax: 1
  config:
    database.hostname: "kafka.database.windows.net"
    database.port: "1433"
    database.user: "${file:/opt/kafka/external-configuration/sql-config/debezium-sql-credentials.properties:sql_username}"
    database.password: "${file:/opt/kafka/external-configuration/sql-config/debezium-sql-credentials.properties:sql_password}"
    database.names: "source1"
    database.server.name: "kafka"
    topic.prefix: "kafka"
    database.history.kafka.bootstrap.servers: "my-cluster-kafka-bootstrap:9092"
    database.history.kafka.topic: "schema-changes.inventory"
    schema.history.internal: "io.debezium.relational.history.MemorySchemaHistory"
