apiVersion: "kafka.strimzi.io/v1beta2"
kind: "KafkaConnector"
metadata:
  name: "s3-sink-connector"
  labels:
    strimzi.io/cluster: kafka-connect-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  class: io.confluent.connect.s3.S3SinkConnector
  tasksMax: 1
  config:
    name: "s3-sink-connector"
    connector.class: "io.confluent.connect.s3.S3SinkConnector"
    storage.class: "io.confluent.connect.s3.storage.S3Storage"
    topics.regex: "source1.source1.*"
    format.class: "io.confluent.connect.s3.format.json.JsonFormat"
    flush.size: "1"
    s3.bucket.name: "kafkastrimzi"
    aws.access.key.id: "${file:/opt/kafka/external-configuration/aws-config/aws-credentials.properties:aws_access_key}"
    aws.secret.access.key: "${file:/opt/kafka/external-configuration/aws-config/aws-credentials.properties:aws_secret_key}"
    s3.region: "us-east-1"
