apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-credentials
  namespace: kafka
spec:
  encryptedData:
    debezium-mysql-credentials.properties: AgB/G9BNmpSPqT+OBbTof/Ny6Ybfi0fhLj69iEHOeYRo8sRsaB4r8fEfdItqI5G5lK+8Yyn88BgluKO3P1R6lm5jFaywcKZ6qePNJ9NTLZsXkCBuDcPJP5QlIFFs620e3Uzj/Dkz+BYA2N67Hy5hHK0L1QKIEC6xZ5Ejo89Rq0+PSAMNVAkYbARno8oUypCMrkCza4L0e5ZPL+LS5+j5bVIipPZ3SBufifVsjc9YS2iyW6oTX0fi7E/jF2LZRFQou6hsbSn0atH1yQHFktO5bt/08abPMHhO7wMBJI6VeQPri7KaXGvgrHFGYY26pO+s6MZeC+o/Sr2FjHFUnVC9jhHOh6o/DA8lNrC/H8dVzFs8t78K7M6CzTCFsl099q08D7ZCkjhiPKEOqpG7YcToHLa/4NU6nytLFK022oA8dIu63O0A2peq0ujLPi0BdAh2kpNpja51Tu4vl5TI1/W2RrjVTPjRnJwK7fJb1FmVpgzFqVQ1kx6S2rs5oSyKEg3DZITtp1zo0dc0PqMt57CxAhRTKyJjHgTxyE3AwkNVX21B5p5P4/nJppmaThw+3EFW5JzvO8oPvmJdecWCp2nZ9j1vTjnAnuW3iDiwHm9SgzVOqYeDIOSMNBigSKvCoyKXaiS+rcuVg6yub+s83TDuq2aCOBTBfxQvF/EmctFEVQDHZX6DDJdVyRI3rEHvjtrmHo/SZCs/bgPVAP7m5wchCSqDkEhBRp9V58JM5SR9a1We427mnO1Qte4Tah0+qiZGY7ePckflhcur
  template:
    metadata:
      creationTimestamp: null
      name: mysql-credentials
      namespace: kafka
    type: Opaque

