apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-credentials
  namespace: kafka
spec:
  encryptedData:
    debezium-mysql-credentials.properties: AgCmgFls0LFiqhYnFXHX0HmGl3mJULA3kH5bqvW+tWw2CnM+OdiLtqSvJFvycSR44tpqmdYViP+APnnp6urCloNa0AyQr9F9dpZkEB1Uj8amfDfGkP7QxFWxnYJAUYGCVI8RYzyzhO3jcV/ogrJS4wbYuSsu+gOP/Lr0xrDdfGECp6jMeDmj83aTq63S1D5zLZz58qm3a3hYXxD3kCJuVRoxNAcUnQsP+sYb4J+bUQmKgi6U6PwX3bAsXDlD9x0Hx6+xRu0dNJWs3qcQJXm5lp577rXDpv1FTxZkewKmyVouv4RCKq34NYj5xwp7Ib9WqHpQzy0drbF/wwK8Seg0So9W9iIJaZ7R0gYV6ft0g+RUJqs7bkNNg5NccjTXXR1CxE5gnA01WmTZzayNqZvPQHnv2/5MfBMOZR4b8nihWszAKzGr15vVMxquh9OFlrr4coYpzxdIGceRrmJUWiMVNvp16nIyUAQaUpB6lBoFUcDWh8be4fvmLfjV8L8tr7A06s5Q7cmsOV9kp+AIIoc857+kpKH3YvQMvFY9KEcb+1QGIH0IQEC6kijoMu0V0zpfjjCiVtDBk43rbOuJwjk05VRMEIKHEjkmpaUsYwIjGdL1C82r5mxNUFZt1Jraz2wHr4peESHWrd99I8lfZTY2Q8aF4RiCm2AlS8nEFHRiZbCcm1F7KJOV/mt9l7F5S/c27KdVeFoZDBBz2hz8bAf6YS+9cUIjr/KfIx+cF4U6eA3fHkPsoSqvA5swQ843pqvKVgLm9UXev/q0
  template:
    metadata:
      creationTimestamp: null
      name: mysql-credentials
      namespace: kafka
    type: Opaque

