apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sql-credentials
  namespace: kafka
spec:
  encryptedData:
    debezium-sql-credentials.properties: AgBHWCbMs0TwnyreMwEER+wessUISsXOmIZn89udEX18Ntg16T4m69d5WFkNMsUJFSIYmuyR2SDSJxpdIeRL/6zkTSJZ9HN29kPQdzchp+0CzXQ/sGDnpnJNQyII++D1DAhWHw9iAynDc0Wf1LLKcPC27v70wVvzggNd60mSTs0KSFGZkI1MTklxkj721Do1HQMobaP8ys4K83p+m1oXRmj2WuDr6Op3ZGSGSZXye6BKKg9BM4UxwBTg8ugi94ouYulyWMeUhKBAJaF32IZ8YonXu/CwyTibRW2kzTGov3DS2+TEz5uph+LDU7oum9WA0lmQ1uaJoBHlCcudTxuj2Q6Xxj3EZQ0KQG8CX7uqW30q9cJn+Hfpr+jmSfX14hEFFc0LO725xdBo5MS9nyQP7lQSRLf927AzEhtf07p8tz+ZY5SkDIklR3ZGmEIAJcxdKrzSFSmd4KcVTFIM7kMC/C58mwEZjrez3JEB3i6PLLWJn6QkcikrSaGQjWQWkXqjPMOLHKHaG4ZK6/WSq2k+2Tkl9CO09TaduLccfiVUTGcq+JVL5uvDBMoVZ4mGVTF+Z+Sl+wW0fWMqLLl28ANBWxNCHfNXxVX4gga8/v2swu4UzG614EGF0g8t/mUXf6URk6wQ2W/pK2sU7CiMrXjz6jWZZ7T+bGGkG6QUAVFdsX8lpLc43TCTQR+z3XgfDaLRuJCeRNLolnljOHl7legZSE2CLbZ7OnnisA73FhyaPX8h3oiwCwEtMlFvo56HWbAJ76bpJA==
  template:
    metadata:
      creationTimestamp: null
      name: sql-credentials
      namespace: kafka
    type: Opaque

