apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-credentials
  namespace: kafka
spec:
  encryptedData:
    debezium-mysql-credentials.properties: AgAol/DTH+31agLhRdjRAMo2T24/M085P0snX5jHyEbtknac3eufGz0Z154cm3OqB4cXvHzsuHkgxbrw85sUKsvVQcp+fVmxDSP4hmfG5NVu0kL/M4sbLfJKuAH8Jm2tZG3D6GPBIHWjoxVMVlTJN8Tp+F2xCJZ/w6Pi85PiEYN5is8fn5HFKwcbv+DqPUUdHSrqEt9FE/wgppam+IPaiaGPwsQNANfM59i/1e2kY7tNa5i12pC9x+Xb0OpPhtLaYmMkJQJlA/LqAOiHpjr8pF6moiPYkTDyXx9dIAKYSJbaviaJWLWhYZbeGrPXdrNGp3YyoVimKrgOmxglqB9nl9g3vg1XMVKChp7eeoKmmH0iyk064puryDh01/5oZbqP+7oSiA+Uh79g0axfYMO068aU1zNiPIsLBCV+oAOqfgIKw7cA13rnyFVnuAkCoqs7JRArzol6+qzxKln19HTU+3gjoyleeH8/KRBD83cMA/wZ4xEoBJpowmB/dAvRrxVaZ6nt/uZcxydtpILBJ4prmt2dUzn/XFPGcyOLlF9MSTwpbeveH6JvXtJ4Na1MXfz03cVwchKxgILKGMo21zxI1APITl7+QZ45d/1iZoGSNlip9QycLbwioqfFprs1KmjIZkHmFlL7WwH68AaIB5YkT5Mq7EqrI64nsb7kqXCvvt7aLcAPJh9/rK8VjYRjbvM/ds7FBzvRNreDeza57+X+aDtrSPcIpSn5LvWQetkXcZcfJzwHJ1b+o76LydVD2uMoQ2XLdLd7aIe1
  template:
    metadata:
      creationTimestamp: null
      name: mysql-credentials
      namespace: kafka
    type: Opaque

