apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-credentials
  namespace: kafka
spec:
  encryptedData:
    debezium-mysql-credentials.properties: AgAr9DYcOn9m6xRblpuLkPO3q9ZJ3j2zMh9L6qs1KM3/596WeEPInHhm2Dge4DVQObOclyWZVSmh/+3wKbcruelbPyM/PZqbaeJdwUMgpU4uYh8RjCN49uKlAlpPeOljcvmzt5ouGBpvu8n1MCWcT6TupVHtMMq4gmZAp9rxN8SXEFdVNZ9sRjeVJlH8prkxtjIKy6u2LqlzliZ452xs9OiI398RVCevUuG7bIC0UM5dCvvJmwq6PxgX88ecMtFh5WKsERXFDiNpPADgK03pHdosozIjMBTbs1isU4XecXc4Pij7bmxsiWCp7qnLeIkLmLkFhQewU9dQ1yPJgmVI1AWe7SAgq1e4DxfMt3dXs9Fa+T6AsLyq2jqDDbYjmwP8YqDb8EBezRXsiCzsf2ent/62Y2DC9YkOnzyS2V8aNLKgyMRq1/Gqo9vL3VOJK9Ig87NGg1t4aIN718QH24UBe+kjim51oug5XG/TdidPHGYWdwBnusyUALrT350YLu4yI4KFbDCHeNmxc+sYj8pzPKW4xeouf6+p8A3MwFI7vAHse8CgudI+5Y7Nm8g1HIGaPMUXA7H9x+Nhwc/kik8WpO4za1P7As1w9r9vyWL5bBwFR04slJ4+gYXGeTv5p+we6zsMf7eU9q81Yuv+z4l4UTWGQC+9DQ/rhDOaMjxPffsCtpMT8HT96a7J6MTCrR4JEY2WdbirqL49OmJfmYU7SSlJbO6IegduSdLF+K7cgmRCe9WPJK78fIl3d4njjWKPn9/AAyoC5LQf
  template:
    metadata:
      creationTimestamp: null
      name: mysql-credentials
      namespace: kafka
    type: Opaque

